server:
  port: 4040
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Nikhita@19
    url: jdbc:mysql://localhost:3306/banking
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
      